services:
  - type: web
    name: id-forgery-detection
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    disk:
      name: data
      mountPath: /app/uploads
      sizeGB: 1
    autoDeploy: true
    domains:
      - id-forgery-detection.onrender.com