services:
  - type: web
    name: id-forgery-detection
    env: docker
    repo: https://github.com/not-cmd/id-forgery-detection.git
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    disk:
      name: data
      mountPath: /app/uploads
      sizeGB: 1
    autoDeploy: true